"""Modular diagram viewer with popup and save options"""
import subprocess
import tempfile
import webbrowser
from pathlib import Path
from typing import Optional

class DiagramViewer:
    """Interactive diagram viewer with popup window"""
    
    @staticmethod
    def view_in_browser(mermaid_code: str, title: str = "FlowClaw Diagram") -> str:
        """Open diagram in browser with Mermaid.js rendering"""
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>{title} - FlowClaw</title>
    <meta charset="UTF-8">
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            margin: 0;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px 30px;
            border-bottom: 1px solid rgba(255,255,255,0.2);
        }}
        .header h1 {{
            margin: 0;
            font-size: 24px;
        }}
        .header p {{
            margin: 5px 0 0;
            opacity: 0.9;
        }}
        .diagram-container {{
            padding: 30px;
            background: #f8f9fa;
            min-height: 500px;
            display: flex;
            justify-content: center;
            align-items: center;
        }}
        .toolbar {{
            padding: 15px 30px;
            background: #fff;
            border-top: 1px solid #e0e0e0;
            display: flex;
            gap: 10px;
            justify-content: flex-end;
        }}
        button {{
            padding: 10px 20px;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-size: 14px;
            font-weight: 500;
            transition: all 0.3s;
        }}
        .btn-primary {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }}
        .btn-primary:hover {{
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(102,126,234,0.4);
        }}
        .btn-secondary {{
            background: #6c757d;
            color: white;
        }}
        .btn-secondary:hover {{
            background: #5a6268;
        }}
        .btn-success {{
            background: #28a745;
            color: white;
        }}
        .btn-success:hover {{
            background: #218838;
        }}
        pre {{
            background: #1e1e1e;
            color: #d4d4d4;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
            font-size: 12px;
        }}
        .mermaid {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}
        .footer {{
            padding: 15px 30px;
            background: #f8f9fa;
            text-align: center;
            font-size: 12px;
            color: #6c757d;
            border-top: 1px solid #e0e0e0;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎨 {title}</h1>
            <p>Generated by FlowClaw AI - Premium Diagram Generator</p>
        </div>
        <div class="diagram-container">
            <pre class="mermaid" id="diagram">
{mermaid_code}
            </pre>
        </div>
        <div class="toolbar">
            <button class="btn-secondary" onclick="downloadAsText()">📄 Download Code</button>
            <button class="btn-success" onclick="saveAsPNG()">📸 Save as PNG</button>
            <button class="btn-primary" onclick="copyToClipboard()">📋 Copy Code</button>
        </div>
        <div class="footer">
            <span>🔍 Tip: Zoom with mouse wheel | Drag to pan | Right-click for more options</span>
        </div>
    </div>
    <script>
        mermaid.initialize({{
            startOnLoad: true,
            theme: 'base',
            themeVariables: {{
                'background': '#ffffff',
                'primaryColor': '#667eea',
                'primaryBorderColor': '#764ba2',
                'primaryTextColor': '#333',
                'lineColor': '#666',
                'secondaryColor': '#f0f0f0',
                'tertiaryColor': '#fff'
            }},
            flowchart: {{
                useMaxWidth: true,
                htmlLabels: true,
                curve: 'basis'
            }},
            securityLevel: 'loose'
        }});
        
        async function downloadAsText() {{
            const diagram = document.getElementById('diagram').textContent;
            const blob = new Blob([diagram], {{type: 'text/plain'}});
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'flowclaw_diagram.mmd';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            alert('✅ Diagram code downloaded!');
        }}
        
        async function saveAsPNG() {{
            try {{
                const svg = document.querySelector('#diagram svg');
                if (!svg) {{
                    alert('Please wait for diagram to render completely');
                    return;
                }}
                const canvas = document.createElement('canvas');
                const ctx = canvas.getContext('2d');
                const data = new XMLSerializer().serializeToString(svg);
                const img = new Image();
                img.onload = () => {{
                    canvas.width = img.width;
                    canvas.height = img.height;
                    ctx.drawImage(img, 0, 0);
                    const png = canvas.toDataURL('image/png');
                    const a = document.createElement('a');
                    a.href = png;
                    a.download = 'flowclaw_diagram.png';
                    document.body.appendChild(a);
                    a.click();
                    document.body.removeChild(a);
                    alert('✅ PNG saved!');
                }};
                img.src = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(data)));
            }} catch(e) {{
                alert('Error saving PNG: ' + e.message);
            }}
        }}
        
        async function copyToClipboard() {{
            const diagram = document.getElementById('diagram').textContent;
            await navigator.clipboard.writeText(diagram);
            alert('✅ Code copied to clipboard!');
        }}
    </script>
</body>
</html>
"""
        # Save to temp file and open
        temp_file = tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False)
        temp_file.write(html_content)
        temp_file.close()
        
        webbrowser.open(f'file://{temp_file.name}')
        return temp_file.name
    
    @staticmethod
    def view_in_terminal(mermaid_code: str) -> str:
        """ASCII preview in terminal (simple)"""
        print("\n" + "="*60)
        print("📊 DIAGRAM PREVIEW (Mermaid Format)")
        print("="*60)
        print(mermaid_code[:1000])
        if len(mermaid_code) > 1000:
            print("\n... (diagram truncated, view in browser for full visualization)")
        print("="*60)
        return mermaid_code[:500]
