"""Simple guaranteed-working popup viewer"""
import webbrowser
import tempfile
from pathlib import Path

class PopupViewer:
    @staticmethod
    def show(code: str, title: str) -> str:
        # Super simple HTML that definitely works
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{title} - FlowClaw</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f0f2f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            padding: 20px;
        }}
        h1 {{
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }}
        .diagram {{
            background: white;
            padding: 20px;
            margin: 20px 0;
            text-align: center;
            overflow-x: auto;
        }}
        button {{
            background: #667eea;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 6px;
            cursor: pointer;
            margin: 5px;
            font-size: 14px;
        }}
        button:hover {{
            background: #5a67d8;
        }}
        .footer {{
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #e0e0e0;
            text-align: center;
            color: #666;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🎨 {title}</h1>
        <div class="diagram">
            <pre class="mermaid">
{code}
            </pre>
        </div>
        <div style="text-align: center;">
            <button onclick="copyCode()">📋 Copy Code</button>
            <button onclick="window.print()">🖨️ Print / Save PDF</button>
        </div>
        <div class="footer">
            Generated by FlowClaw AI | Mermaid v10
        </div>
    </div>
    <script>
        mermaid.initialize({{
            startOnLoad: true,
            theme: 'default',
            securityLevel: 'loose',
            flowchart: {{
                useMaxWidth: true,
                htmlLabels: true
            }}
        }});
        
        function copyCode() {{
            const code = document.querySelector('.mermaid').textContent;
            navigator.clipboard.writeText(code).then(() => {{
                alert('✅ Diagram code copied to clipboard!');
            }});
        }}
        
        // Refresh mermaid after load
        window.addEventListener('load', function() {{
            mermaid.contentLoaded();
        }});
    </script>
</body>
</html>"""
        
        # Write to temp file
        temp_file = tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False, encoding='utf-8')
        temp_file.write(html)
        temp_file.close()
        
        # Open in browser
        webbrowser.open(f'file://{temp_file.name}')
        return temp_file.name
