"""Base exporter interface"""
from abc import ABC, abstractmethod
from pathlib import Path
from datetime import datetime

class BaseExporter(ABC):
    @abstractmethod
    def export(self, code: str, output_path: Path, title: str) -> bool:
        pass

class DocxExporter(BaseExporter):
    def export(self, code: str, output_path: Path, title: str) -> bool:
        html = f'''<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>{title}</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
</head><body><h1>{title}</h1><pre class="mermaid">{code}</pre>
<script>mermaid.initialize({{startOnLoad:true}});</script></body></html>'''
        output_path.with_suffix('.docx').write_text(html)
        return True

class PdfExporter(BaseExporter):
    def export(self, code: str, output_path: Path, title: str) -> bool:
        html = f'''<!DOCTYPE html>
<html><head><title>{title}</title><style>@media print{{body{{margin:0}}}}</style>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
</head><body><h1>{title}</h1><pre class="mermaid">{code}</pre>
<div><button onclick="window.print()">Save as PDF</button></div>
<script>mermaid.initialize({{startOnLoad:true}});</script></body></html>'''
        output_path.with_suffix('.html').write_text(html)
        return True

class MarkdownExporter(BaseExporter):
    def export(self, code: str, output_path: Path, title: str) -> bool:
        md = f"# {title}\n\n```mermaid\n{code}\n```\n\n---\n*Generated by FlowClaw on {datetime.now()}*"
        output_path.with_suffix('.md').write_text(md)
        return True

class HtmlExporter(BaseExporter):
    def export(self, code: str, output_path: Path, title: str) -> bool:
        html = f'''<!DOCTYPE html>
<html><head><title>{title}</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<style>.mermaid{{text-align:center;padding:20px}}</style>
</head><body><h1>{title}</h1><pre class="mermaid">{code}</pre>
<script>mermaid.initialize({{startOnLoad:true}});</script></body></html>'''
        output_path.with_suffix('.html').write_text(html)
        return True

class JsonExporter(BaseExporter):
    def export(self, code: str, output_path: Path, title: str) -> bool:
        import json
        data = {'title': title, 'code': code, 'generated': datetime.now().isoformat()}
        output_path.with_suffix('.json').write_text(json.dumps(data, indent=2))
        return True
