from pathlib import Path
base = Path('.'); V={'Allen':'https://www.allencountyohio.com/','Ashland':'https://www.ashlandcounty.org/','Ashtabula':'https://www.ashtabulacounty.us/','Belmont':'https://www.belmontcountyohio.org/','Brown':'https://www.browncountyohio.gov/','Butler':'https://www.butlercountyohio.org/','Carroll':'https://www.carrollcountyohio.us/','Champaign':'https://www.co.champaign.oh.us/','Clark':'https://www.clarkcountyohio.gov/','Clermont':'https://www.clermontcountyohio.gov/','Clinton':'https://www.clintoncountyohio.com/','Coshocton':'https://www.coshoctoncounty.net/','Cuyahoga':'https://www.cuyahogacounty.gov/','Darke':'https://www.darkecountyohio.com/','Defiance':'https://www.defiance-county.com/','Delaware':'https://www.co.delaware.oh.us/','Erie':'https://www.eriecounty.oh.gov/','Fairfield':'https://www.co.fairfield.oh.us/','Fayette':'https://www.fayette-co-oh.com/','Fulton':'https://www.fultoncountyoh.com/','Gallia':'https://www.galliacounty.org/','Greene':'https://www.greenecountyohio.gov/','Guernsey':'https://www.guernseycounty.org/','Hamilton':'https://www.hamiltoncountyohio.gov/','Harrison':'https://www.harrisoncountyohio.org/','Henry':'https://www.henrycountyohio.com/','Lake':'https://www.lakecountyohio.gov/','Licking':'https://www.lickingcounty.gov/','Lucas':'https://www.co.lucas.oh.us/','Madison':'https://www.co.madison.oh.us/','Mahoning':'https://www.mahoningcountyoh.gov/','Marion':'https://www.co.marion.oh.us/','Mercer':'https://www.mercercountyohio.org/','Miami':'https://www.miamicountyohio.gov/','Monroe':'https://www.monroecountyohio.com/','Montgomery':'https://www.mcohio.org/','Morrow':'https://www.morrowcountyohio.gov/','Noble':'https://www.noblecountyohio.gov/','Paulding':'https://www.pauldingcountyoh.com/','Perry':'https://www.perrycountyohio.net/','Pickaway':'https://www.pickawaycountyohio.gov/','Preble':'https://www.prebco.org/','Putnam':'https://www.putnamcountyohio.gov/','Ross':'https://www.rosscountyohio.gov/','Seneca':'https://www.senecacountyohio.gov/','Shelby':'https://www.shelbycountyohio.com/','Stark':'https://www.starkcountyohio.gov/','Summit':'https://www.summitoh.net/','Trumbull':'https://www.co.trumbull.oh.us/','Tuscarawas':'https://www.co.tuscarawas.oh.us/','Union':'https://www.unioncountyohio.gov/','Van_Wert':'https://www.vanwertcountyohio.gov/','Washington':'https://www.washingtongov.org/','Wayne':'https://www.wayneohio.org/','Wood':'https://www.woodcountyohio.gov/'}
b5=[('Jefferson','Steubenville','(740)283-8500'),('Knox','Mount Vernon','(740)393-6700'),('Lake','Painesville','(440)350-2500'),('Lawrence','Ironton','(740)533-4300'),('Licking','Newark','(740)670-5000'),('Logan','Bellefontaine','(937)599-7200'),('Lorain','Elyria','(440)329-5000'),('Lucas','Toledo','(419)213-4000'),('Madison','London','(740)852-1900'),('Mahoning','Youngstown','(330)740-2000')]
for d,s,p in b5:
    u=V.get(d); d2=base/d; d2.mkdir(exist_ok=True)
    ul=f'## URL: {u} (verified)' if u else '## URL: No verified website found'
    (d2/'building_code.md').write_text(f'# {d} County - Ohio\n## County Seat: {s}\n## Phone: {p}\n{ul}\n\n## OH Building Code\nIBC 2018 | IRC 2018 | NEC 2017 | IPC 2018 | IMC 2018 | IFC 2018 | IECC 2018\n\n## Design Criteria\nFrost: 30-42 in | Snow: 20-35 psf | Wind: 115 mph | Seismic: SDC A-B\n\n## State Resources\nOH BBS: (614) 644-2613 | https://www.com.ohio.gov/\n',encoding='utf-8')
    print(f'Wrote: {d}')
print('B5 done')
