"""Preview Generator - Creates HTML visualizations of designs"""
from pathlib import Path
import webbrowser

class PreviewGenerator:
    """Generates HTML previews for design concepts"""
    
    def __init__(self, exports_dir: Path):
        self.exports_dir = exports_dir
        self.exports_dir.mkdir(parents=True, exist_ok=True)
    
    def brand_identity(self, name: str, colors: list, fonts: dict, concept: str) -> str:
        """Generate HTML preview for brand identity"""
        timestamp = __import__('datetime').datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"brand_{name.replace(' ', '_')}_{timestamp}.html"
        filepath = self.exports_dir / filename
        
        html = f'''<!DOCTYPE html>
<html>
<head>
    <title>DesignClaw: {name}</title>
    <link href="{fonts.get('header', 'Inter')}" rel="stylesheet">
    <link href="{fonts.get('body', 'Open Sans')}" rel="stylesheet">
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: '{fonts.get("body", "Open Sans")}', sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 40px 20px;
        }}
        .preview-card {{
            max-width: 800px;
            margin: 0 auto;
            background: white;
            border-radius: 24px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }}
        .header {{
            background: {colors[0]};
            padding: 60px 40px;
            text-align: center;
        }}
        .header h1 {{
            font-family: '{fonts.get("header", "Inter")}', sans-serif;
            color: white;
            font-size: 3em;
            margin-bottom: 10px;
        }}
        .header .tagline {{
            color: rgba(255,255,255,0.9);
            font-size: 1.2em;
        }}
        .colors {{
            display: flex;
            padding: 20px;
            gap: 10px;
            background: {colors[3]};
        }}
        .color-swatch {{
            flex: 1;
            height: 80px;
            border-radius: 12px;
            display: flex;
            align-items: flex-end;
            justify-content: center;
            padding: 10px;
            font-family: monospace;
            font-size: 12px;
            color: white;
            text-shadow: 0 1px 3px rgba(0,0,0,0.3);
        }}
        .content {{
            padding: 40px;
        }}
        .concept {{
            background: {colors[3]};
            padding: 20px;
            border-radius: 12px;
            margin-top: 20px;
        }}
        .footer {{
            padding: 20px 40px;
            background: {colors[1]};
            color: white;
            text-align: center;
            font-size: 0.9em;
        }}
        .btn {{
            display: inline-block;
            padding: 12px 24px;
            background: {colors[0]};
            color: white;
            text-decoration: none;
            border-radius: 8px;
            margin: 10px;
            transition: transform 0.2s;
        }}
        .btn:hover {{ transform: scale(1.05); }}
    </style>
</head>
<body>
    <div class="preview-card">
        <div class="header">
            <h1>{name}</h1>
            <div class="tagline">Brand Identity Concept</div>
        </div>
        <div class="colors">
            {''.join(f'<div class="color-swatch" style="background: {c};">{c}</div>' for c in colors)}
        </div>
        <div class="content">
            <h2 style="font-family: '{fonts.get("header")}'; color: {colors[0]};">Design Concept</h2>
            <div class="concept">{concept.replace(chr(10), '<br>')}</div>
            <div style="margin-top: 30px; text-align: center;">
                <a href="#" class="btn">Primary Action</a>
                <a href="#" class="btn" style="background: {colors[1]};">Secondary</a>
            </div>
        </div>
        <div class="footer">
            Generated by DesignClaw • {__import__('datetime').datetime.now().strftime("%B %d, %Y")}
        </div>
    </div>
</body>
</html>'''
        
        filepath.write_text(html, encoding='utf-8')
        return str(filepath)
    
    def mood_board(self, name: str, colors: list, mood: str, description: str) -> str:
        """Generate mood board HTML preview"""
        timestamp = __import__('datetime').datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"mood_{name.replace(' ', '_')}_{timestamp}.html"
        filepath = self.exports_dir / filename
        
        gradient = f"linear-gradient(135deg, {colors[0]}, {colors[1] if len(colors) > 1 else colors[0]})"
        
        html = f'''<!DOCTYPE html>
<html>
<head>
    <title>Mood: {name}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: system-ui, -apple-system, sans-serif;
            background: {gradient};
            min-height: 100vh;
            padding: 40px 20px;
        }}
        .mood-card {{
            max-width: 600px;
            margin: 0 auto;
            background: rgba(255,255,255,0.95);
            backdrop-filter: blur(10px);
            border-radius: 32px;
            padding: 40px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.2);
        }}
        h1 {{
            font-size: 3em;
            margin-bottom: 10px;
            background: {gradient};
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}
        .mood-tag {{
            display: inline-block;
            padding: 8px 16px;
            background: {colors[0]};
            color: white;
            border-radius: 20px;
            font-size: 0.9em;
            margin-bottom: 30px;
        }}
        .colors {{
            display: flex;
            gap: 15px;
            margin: 30px 0;
        }}
        .color-dot {{
            width: 60px;
            height: 60px;
            border-radius: 50%;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }}
        .description {{
            line-height: 1.8;
            color: #333;
            margin: 30px 0;
            padding: 20px;
            background: rgba(0,0,0,0.03);
            border-radius: 16px;
        }}
    </style>
</head>
<body>
    <div class="mood-card">
        <span class="mood-tag">{mood.upper()}</span>
        <h1>{name}</h1>
        <div class="colors">
            {''.join(f'<div class="color-dot" style="background: {c};" title="{c}"></div>' for c in colors)}
        </div>
        <div class="description">{description}</div>
        <p style="color: #999; font-size: 0.8em;">Generated by DesignClaw • {__import__('datetime').datetime.now().strftime("%B %d, %Y")}</p>
    </div>
</body>
</html>'''
        
        filepath.write_text(html, encoding='utf-8')
        return str(filepath)
    
    def open_preview(self, filepath: str):
        """Open the preview in browser"""
        webbrowser.open(f"file://{filepath}")
