#!/usr/bin/env python3
print("=" * 60)
print("  CLAWPACK V2 - SYSTEM ONBOARDING")
print("=" * 60)
print()
print("21-agent local AI runtime. A2A message bus port 8766.")
print("Constitutional governance. Chronicle FTS5. Sovereign Gateway.")
print("Advanced Alpha. 5/10 Beta gates passed.")
print()
print("GETTING STARTED:")
print("  1. Read POWERSHELL_SURVIVAL_GUIDE.md first")
print("  2. Read CLAWPACK_ONBOARD.md for full system context")
print("  3. Read docs/WEBCLAW_ARCHITECTURE.md for knowledge system")
print("  4. Read each agent's README.md before working on it")
print("  5. Start server: python a2a_server.py")
print("  6. Launch menu: python clawpack.py")
print('  7. Test server: python -c "import requests; r=requests.post(\'http://127.0.0.1:8766/v1/message/lawclaw\',json={\'task\':\'/stats\'},timeout=10); print(r.status_code)"')
print()
print("READING ORDER (read in this exact sequence):")
print("  1. POWERSHELL_SURVIVAL_GUIDE.md - How to work in this environment")
print("  2. CLAWPACK_ONBOARD.md - Architecture, rules, session log, next mission")
print("  3. docs/WEBCLAW_MANUAL.md - Complete WebClaw guide (READ FIRST before any agent work)")
print("  4. shared/CONSTITUTION_v1.md - Supreme law (NON-NEGOTIABLE)")
print("  5. BASEAGENT_GUIDE.md - What every agent inherits")
print("  6. AGENT_CAPABILITIES.md - Which agent owns which capability")
print("  7. CHRONICLE_GUIDE.md - How the knowledge database works")
print("  8. DECISION_LOG.md - Why architectural decisions were made")
print("  9. docs/reports/STATE_OF_CLAWPACK_V2_2026_06_02.md - Audit snapshot")
print("")
print("BEFORE WORKING ON ANY AGENT, read:")
print("  agents/<name>/README.md (21 files, one per agent)")
print("")
print("KEY SOURCE FILES:")
print("  shared/base_agent.py - Foundation class")
print("  shared/_agent_helpers.py - Stateless utilities")
print("  shared/llm/client.py - Sovereign Gateway")
print("  shared/capabilities.py - Command routing")
print("  shared/query_normalizer.py - Location extraction")
print("  a2a_server.py - Central message bus")
print("  clawpack.py - Primary menu")
print()
print("CRITICAL RULES:")
print("  1. NEVER python -c with multi-line code")
print("  2. NEVER PowerShell heredocs with Python")
print("  3. Deploy: write command file once, Copy-Item")
print("  4. NEVER batch-inject into handlers (May 30)")
print("  5. ALWAYS clear __pycache__ after shared changes")
print("  6. All LLM through Sovereign Gateway only")
print("  7. except: pass is UNCONSTITUTIONAL")
print()
print("SERVER COMMANDS:")
print("  Start: python a2a_server.py")
print("  Kill all: taskkill /F /IM python.exe")
print("  Clear cache: Get-ChildItem -Recurse -Directory -Filter __pycache__ | Remove-Item -Recurse -Force")
print('  Test: python -c "import requests; r=requests.post(\'http://127.0.0.1:8766/v1/message/lawclaw\',json={\'task\':\'/stats\'},timeout=10); print(r.status_code)"')
print()
print("ARCHITECTURE:")
print("  Layer 1: A2A Server (a2a_server.py, port 8766)")
print("  Layer 2: Shared Infrastructure (93+ modules)")
print("  Layer 3: 21 Specialized Agents (agents/)")
print()

print("AGENT DOCUMENTATION:")
print("  Each agent has a README.md with full purpose, design, and commands:")
print("  agents/lawclaw/README.md         - Legal research, 31 commands, gold standard")
print("  agents/claw_coder/README.md      - Code generation, 39 languages")
print("  agents/interpretclaw/README.md   - Translation, 42 languages, TTS/Braille")
print("  agents/mathematicaclaw/README.md - Math engine, SymPy + Plotly")
print("  agents/webclaw/README.md         - Information backbone, Chronicle owner")
print("  agents/llmclaw/README.md         - Model manager, Sovereign Gateway")
print("  agents/flowclaw/README.md        - Diagrams, Mermaid.js, browser viewer")
print("  agents/docuclaw/README.md        - Document creation, 21 format exports")
print("  agents/plotclaw/README.md        - Charts, 13 chart types, matplotlib")
print("  agents/dataclaw/README.md        - Local data search, 41K files, cache")
print("  agents/crustyclaw/README.md      - Rust audit, standalone binary bridge")
print("  agents/mediclaw/README.md        - Medical diagnosis, hospital geolocation")
print("  agents/liberateclaw/README.md    - Model liberation, obliterated models")
print("  agents/txclaw/README.md          - TX Blockchain, smart contracts")
print("  agents/langclaw/README.md        - Language teaching, TTS/STT")
print("  agents/designclaw/README.md      - Brand identity, color palettes")
print("  agents/draftclaw/README.md       - Building permits, 4,744 jurisdictions")
print("  agents/drawclaw/README.md        - AI drawing, 14 art commands")
print("  agents/dreamclaw/README.md       - AI vision generation")
print("  agents/fileclaw/README.md        - File operations, 41+ formats")
print("  agents/rustypycraw/README.md     - Code crawler, AST analysis")
print("")
print("READ THESE before working on any agent.")
print("")
print("  PROJECT README (README.md):")
print("    Full agent table grouped by Domain/Utility/Infrastructure")

print("WEBCLAW - CENTRAL KNOWLEDGE SYSTEM:")
print("  Live Web Fetching + Chronicle FTS5 + Reference Corpus")
print("  35,000+ files, 50 states, 3,000+ counties, 3,800+ cities")
print("  CRITICAL: namespace-scope searches to prevent contamination")
print()
print("PROVIDER CHAIN: Ollama(gemma3:4b) -> Groq -> OpenRouter -> Anthropic")
print("ENFORCEMENT: Active at HTTP boundary (6 patterns blocked)")
print("RUNTIME: runtime/ (gitignored), data/ (static refs only)")
print()
print("AGENTS WORKING: lawclaw, claw_coder, interpretclaw, mathematicaclaw,")
print("  webclaw, llmclaw, flowclaw, docuclaw")
print("AGENTS PARTIAL: plotclaw, dataclaw, crustyclaw, mediclaw, liberateclaw")
print("AGENTS UNTESTED: txclaw, langclaw, designclaw, draftclaw, drawclaw,")
print("  dreamclaw, fileclaw, rustypycraw")
print()
print("KNOWN ISSUES:")
print("  CRITICAL: WebClaw cross-domain contamination")
print("  HIGH: FlowClaw 13 variants, 6 agents with duplicates")
print("  MEDIUM: Obliterated models not via standard Ollama")
print()
print("NEXT MISSION:")
print("  Priority 6: Codebase consolidation")
print("  Priority 7: Security assessment")
print("  Infrastructure: WebClaw namespace-scoped search")
print()
print("=" * 60)
print("  ONBOARDING COMPLETE")
print("=" * 60)