#!/usr/bin/env python3
print("=" * 60)
print("  CLAWPACK V2 - SYSTEM ONBOARDING")
print("=" * 60)
print()
print("21-agent local AI runtime. A2A message bus port 8766.")
print("Constitutional governance. Chronicle FTS5. Sovereign Gateway.")
print("Advanced Alpha. 5/10 Beta gates passed.")
print()
print("READ THESE FIRST:")
print("  docs/WEBCLAW_ARCHITECTURE.md")
print("  CLAWPACK_ONBOARD.md")
print("  POWERSHELL_SURVIVAL_GUIDE.md")
print()
print("CRITICAL RULES:")
print("  1. NEVER python -c with multi-line code")
print("  2. NEVER PowerShell heredocs with Python")
print("  3. Deploy: write command file once, Copy-Item")
print("  4. NEVER batch-inject into handlers (May 30)")
print("  5. ALWAYS clear __pycache__ after shared changes")
print("  6. All LLM through Sovereign Gateway only")
print("  7. except: pass is UNCONSTITUTIONAL")
print()
print("ARCHITECTURE:")
print("  Layer 1: A2A Server (a2a_server.py, port 8766)")
print("  Layer 2: Shared Infrastructure (93+ modules)")
print("  Layer 3: 21 Specialized Agents (agents/)")
print()

print("AGENT DOCUMENTATION:")
print("  Each agent has a README.md with full purpose, design, and commands:")
print("  agents/lawclaw/README.md         - Legal research, 31 commands, gold standard")
print("  agents/claw_coder/README.md      - Code generation, 39 languages")
print("  agents/interpretclaw/README.md   - Translation, 42 languages, TTS/Braille")
print("  agents/mathematicaclaw/README.md - Math engine, SymPy + Plotly")
print("  agents/webclaw/README.md         - Information backbone, Chronicle owner")
print("  agents/llmclaw/README.md         - Model manager, Sovereign Gateway")
print("  agents/flowclaw/README.md        - Diagrams, Mermaid.js, browser viewer")
print("  agents/docuclaw/README.md        - Document creation, 21 format exports")
print("  agents/plotclaw/README.md        - Charts, 13 chart types, matplotlib")
print("  agents/dataclaw/README.md        - Local data search, 41K files, cache")
print("  agents/crustyclaw/README.md      - Rust audit, standalone binary bridge")
print("  agents/mediclaw/README.md        - Medical diagnosis, hospital geolocation")
print("  agents/liberateclaw/README.md    - Model liberation, obliterated models")
print("  agents/txclaw/README.md          - TX Blockchain, smart contracts")
print("  agents/langclaw/README.md        - Language teaching, TTS/STT")
print("  agents/designclaw/README.md      - Brand identity, color palettes")
print("  agents/draftclaw/README.md       - Building permits, 4,744 jurisdictions")
print("  agents/drawclaw/README.md        - AI drawing, 14 art commands")
print("  agents/dreamclaw/README.md       - AI vision generation")
print("  agents/fileclaw/README.md        - File operations, 41+ formats")
print("  agents/rustypycraw/README.md     - Code crawler, AST analysis")
print("")
print("READ THESE before working on any agent.")
print("")
print("  PROJECT README (README.md):")
print("    Full agent table grouped by Domain/Utility/Infrastructure")

print("WEBCLAW - CENTRAL KNOWLEDGE SYSTEM:")
print("  Live Web Fetching + Chronicle FTS5 + Reference Corpus")
print("  35,000+ files, 50 states, 3,000+ counties, 3,800+ cities")
print("  CRITICAL: namespace-scope searches to prevent contamination")
print()
print("PROVIDER CHAIN: Ollama(gemma3:4b) -> Groq -> OpenRouter -> Anthropic")
print("ENFORCEMENT: Active at HTTP boundary (6 patterns blocked)")
print("RUNTIME: runtime/ (gitignored), data/ (static refs only)")
print()
print("AGENTS WORKING: lawclaw, claw_coder, interpretclaw, mathematicaclaw,")
print("  webclaw, llmclaw, flowclaw, docuclaw")
print("AGENTS PARTIAL: plotclaw, dataclaw, crustyclaw, mediclaw, liberateclaw")
print("AGENTS UNTESTED: txclaw, langclaw, designclaw, draftclaw, drawclaw,")
print("  dreamclaw, fileclaw, rustypycraw")
print()
print("KNOWN ISSUES:")
print("  CRITICAL: WebClaw cross-domain contamination")
print("  HIGH: FlowClaw 13 variants, 6 agents with duplicates")
print("  MEDIUM: Obliterated models not via standard Ollama")
print()
print("NEXT MISSION:")
print("  Priority 6: Codebase consolidation")
print("  Priority 7: Security assessment")
print("  Infrastructure: WebClaw namespace-scoped search")
print()
print("=" * 60)
print("  ONBOARDING COMPLETE")
print("=" * 60)