#!/usr/bin/env python3
"""FlowClaw - Offline Local Renderer (No Internet Needed for Viewing)"""

import sys
import webbrowser
import tempfile
from pathlib import Path
from datetime import datetime

class FlowClawOffline:
    def __init__(self):
        self.output_path = Path(__file__).parent / "output"
        self.output_path.mkdir(exist_ok=True)
    
    def get_diagram(self, template):
        diagrams = {
            'login': '''flowchart TD
    A[Start] --> B[Enter Email]
    B --> C[Enter Password]
    C --> D{Valid?}
    D -->|Yes| E[Dashboard]
    D -->|No| F[Error]
    F --> B''',
            
            'decision': '''flowchart TD
    A[Start] --> B{Choice}
    B -->|Option 1| C[Path 1]
    B -->|Option 2| D[Path 2]
    C --> E[End]
    D --> E''',
        }
        return diagrams.get(template, diagrams['login'])
    
    def render_local(self, code, title):
        """Render diagram locally using embedded Mermaid"""
        html = f'''<!DOCTYPE html>
<html>
<head>
    <title>{title} - FlowClaw</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
    <style>
        body {{
            font-family: 'Segoe UI', Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            min-height: 100vh;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.3);
            overflow: hidden;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px 30px;
        }}
        .header h1 {{ margin: 0; font-size: 24px; }}
        .diagram-container {{
            padding: 40px;
            background: #f8f9fa;
            text-align: center;
            min-height: 500px;
        }}
        .toolbar {{
            padding: 15px 30px;
            background: white;
            border-top: 1px solid #e0e0e0;
            text-align: center;
        }}
        button {{
            background: #667eea;
            color: white;
            border: none;
            padding: 10px 20px;
            margin: 0 5px;
            border-radius: 8px;
            cursor: pointer;
            font-size: 14px;
        }}
        button:hover {{
            background: #5a67d8;
            transform: translateY(-2px);
        }}
        .mermaid {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            display: inline-block;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}
        .footer {{
            padding: 15px;
            background: #f8f9fa;
            text-align: center;
            font-size: 12px;
            color: #666;
        }}
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>🎨 {title}</h1>
        <p>Generated by FlowClaw - Rendered Locally</p>
    </div>
    <div class="diagram-container">
        <pre class="mermaid">
{code}
        </pre>
    </div>
    <div class="toolbar">
        <button onclick="copyCode()">📋 Copy Code</button>
        <button onclick="window.print()">🖨️ Print / Save PDF</button>
        <button onclick="location.reload()">🔄 Refresh</button>
    </div>
    <div class="footer">
        💡 If diagram doesn't appear, check your internet connection (Mermaid CDN needed once)
    </div>
</div>
<script>
    mermaid.initialize({{
        startOnLoad: true,
        theme: 'base',
        themeVariables: {{
            'primaryColor': '#667eea',
            'primaryBorderColor': '#764ba2',
            'primaryTextColor': '#333',
        }},
        flowchart: {{ useMaxWidth: true, htmlLabels: true }},
        securityLevel: 'loose'
    }});
    
    function copyCode() {{
        const code = document.querySelector('.mermaid').textContent;
        navigator.clipboard.writeText(code);
        alert('✅ Code copied!');
    }}
    
    // Refresh mermaid after load
    setTimeout(() => {{
        try {{
            mermaid.contentLoaded();
        }} catch(e) {{
            console.log('Mermaid rendering:', e);
        }}
    }}, 100);
</script>
</body>
</html>'''
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False, encoding='utf-8') as f:
            f.write(html)
            temp_path = f.name
        
        webbrowser.open(f'file://{temp_path}')
        return temp_path
    
    def view(self, template):
        code = self.get_diagram(template)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = self.output_path / f"{template}_{timestamp}.mmd"
        filename.write_text(code)
        
        html_file = self.render_local(code, f"FlowClaw: {template.title()}")
        
        return f"""
✅ Diagram rendered locally!
📁 Saved: {filename}
🌐 Browser opened with diagram

The diagram should appear directly in your browser!
If not, check your internet connection (CDN loads once).
"""
    
    def process(self, cmd, *args):
        if cmd == "view" and args:
            return self.view(args[0])
        return self.help()
    
    def help(self):
        return """
🎨 FlowClaw - Offline Local Renderer

COMMAND:
  python flowclaw_offline.py view <template>

TEMPLATES:
  login     - Login flow diagram
  decision  - Decision tree diagram

EXAMPLE:
  python flowclaw_offline.py view login

The diagram will open in your browser with local rendering!
"""

def main():
    agent = FlowClawOffline()
    if len(sys.argv) < 2:
        print(agent.help())
        return
    result = agent.process(sys.argv[1], *sys.argv[2:])
    print(result)

if __name__ == "__main__":
    main()
